//! Load embedded catalog and digests (pure load).
//!
//! Until MS-007 embeds the closed catalog, Construct uses an in-memory
//! **stub catalog** (`stub_catalog`) so plan/generate pipeline and goldens can
//! exist. Replace the stub body without changing [`CatalogView`] / Construct
//! signatures.
//!
//! Does not import `plan` (avoids catalog ↔ plan cycles); Construct maps modes.

/// Placeholder catalog digest until MS-007 embeds a real closed catalog.
pub const STUB_CATALOG_DIGEST: &str = "stub-catalog-v0-unembedded";

/// Emit mode recorded on a catalog template entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CatalogFileMode {
    /// Regular file.
    File,
    /// Executable file.
    Executable,
    /// Directory entry.
    Directory,
}

/// One catalog template file (relative path + body bytes as UTF-8 text).
///
/// Bodies may include simple `{{name}}` placeholders expanded at Construct.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CatalogFile {
    /// Relative path under project root (forward slashes; no `..` / absolute).
    pub path: String,
    /// Emit mode.
    pub mode: CatalogFileMode,
    /// Template body (UTF-8).
    pub body: String,
}

/// In-memory catalog view passed to pure Construct (no I/O at construct time).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CatalogView {
    /// Catalog content digest bound to this view.
    pub digest: String,
    /// Template files in deterministic order.
    pub files: Vec<CatalogFile>,
}

/// Minimal pure-CLI fixture tree for PHASE-01 (pre-embed).
///
/// Documented stub: README + Cargo.toml + src/main.rs + AGENTS.md skeleton.
/// MS-007/MS-008 replace content; digest string remains the stub token until embed.
pub fn stub_catalog() -> CatalogView {
    CatalogView {
        digest: STUB_CATALOG_DIGEST.to_string(),
        files: vec![
            CatalogFile {
                path: "Cargo.toml".into(),
                mode: CatalogFileMode::File,
                body: r#"[package]
name = "{{name}}"
version = "0.1.0"
edition = "2021"
description = "Generated by rust-foundry (stub catalog)"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
"#
                .into(),
            },
            CatalogFile {
                path: "src/main.rs".into(),
                mode: CatalogFileMode::File,
                body: r#"//! {{name}} — generated pure CLI (stub catalog).

fn main() {
    println!("{{name}}");
}
"#
                .into(),
            },
            CatalogFile {
                path: "README.md".into(),
                mode: CatalogFileMode::File,
                body: "# {{name}}\n\nGenerated by rust-foundry stub catalog (PHASE-01).\n".into(),
            },
            CatalogFile {
                path: "AGENTS.md".into(),
                mode: CatalogFileMode::File,
                body: "# AGENTS.md\n\nProject: {{name}}\n\nFollow repo quality gates (`cargo fmt`, `clippy -D warnings`, `cargo test`).\n".into(),
            },
            CatalogFile {
                path: ".gitignore".into(),
                mode: CatalogFileMode::File,
                body: "/target/\n".into(),
            },
        ],
    }
}
